---

-   name: Download node exporter
    get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
        dest: .

-   name: Extract node exprter
    unarchive:
        src: node_exporter-1.0.1.linux-amd64.tar.gz
        dest: .

-   name: create node_exporter user
    command: sudo useradd -rs /bin/false node_exporter

-   name: Copy the binary to your /usr/local/bin folder
    copy:
        src: /node_exporter-1.0.1.linux-amd64/node_exporter
        dest: /usr/local/bin/
        owner: node_exporter
        group: node_exporter
        mode: '0644'

-   name: Template node exporter service config
    template:
        src: node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
        owner: "{{server_user}}"
        group: "{{server_user}}"
        mode: "0644"

-   name: reload deamon
    command: sudo systemctl daemon-reload

-   name: start node exporter service
    command: sudo systemctl start node_exporter

-   name: check status of node Exporter
    command: sudo systemctl status node_exporter.service

-   name: enable start of service on boot
    command: sudo systemctl enable node_exporter

-   name: Download Prometheus
    get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.23.0/prometheus-2.23.0.linux-amd64.tar.gz
        dest: .

-   name: Extract Prometheus
    unarchive:
        src: prometheus-2.23.0.linux-amd64.tar.gz
        dest: .

-   name: Template prometheus config
    template:
        src: prometheus.yml.j2
        dest: prometheus-2.23.0.linux-amd64/prometheus.yml
        owner: "{{server_user}}"
        group: "{{server_user}}"
        mode: "0644"

-   name: Launch prometheus
    command:
        cd /prometheus-2.23.0.linux-amd64 \
        ./prometheus &

-   name: Download grafana
    get_url:
        url: https://dl.grafana.com/oss/release/grafana_7.3.4_amd64.deb
        dest: .

-   name: Extract grafana deb
    command: sudo dpkg -i grafana_7.3.4_amd64.deb
