---
- name: Create security group
  ec2_group:
    name: "{{ group.name }}"
    description: The Webserver security group
    region: "{{ region }}"
    rules: "{{ group.port_rules }}"
    rules_egress: # outgoing traffic
      - proto: all
        cidr_ip: 0.0.0.0/0
    state: present
  loop: "{{ sg_groups }}"
  loop_control: 
    loop_var: group
  delegate_to: 127.0.0.1
