version: '3.8'
services:
    test:
        container_name: microblog_test
        build:
          dockerfile: docker/Dockerfile_test
          context: .
        volumes:
          - "./tests:/home/test/tests"
          - "./app:/home/test/app"
    prod:
        env_file:
            - .env
        container_name: microblog
        image: osln17/microblog:latest
        restart: always
        environment:
            - MYSQL_DATABASE=microblog
            - DATABASE_URL=${URL}
        ports:
            - "8000:5000"
        depends_on:
            - mysql
        networks:
            microblog:
    mysql:
        container_name: microblog_db
        env_file:
            - .env
        restart: always
        image: mysql/mysql-server:8.0
        expose:
            - "3306"
        environment:
            - MYSQL_DATABASE=microblog
            - MYSQL_USER=microblog
            - MYSQL_PASSWORD=${DATABASE_PASS}
        volumes:
            - microblog-data:/var/lib/mysql
        command: --innodb-use-native-aio=0
        networks:
            microblog:
networks:
    microblog:
volumes:
  microblog-data:
    driver: local
