DROP USER IF EXISTS 'exporter'@'%';
FLUSH PRIVILEGES;
CREATE USER 'exporter'@'%' IDENTIFIED BY 'pass' WITH MAX_USER_CONNECTIONS 3;
GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'%';
GRANT SELECT ON performance_schema.* TO 'exporter'@'%';
