FROM python:3.6-alpine
RUN adduser -D microblog

WORKDIR /home/microblog

# COPY . .
COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py no-statsd.sh ./

RUN python -m venv .venv
ENV FLASK_APP microblog.py
RUN apk add --update --virtual build-dependencies libffi-dev openssl-dev py-pip build-base \
  && .venv/bin/pip3 install --upgrade pip \
  && .venv/bin/pip3 install -r requirements.txt \
  && .venv/bin/pip3 install --no-cache-dir cryptography==2.1.4
RUN chmod +x no-statsd.sh

RUN chown -R microblog:microblog ./
USER microblog

EXPOSE 5000
ENTRYPOINT ["./no-statsd.sh"]
