---
-   name: Launch the new EC2 Instance
    ec2:
        group: "{{ item.security_group }}"
        instance_type: "{{ item.instance_type }}"
        instance_tags: "{{ item.instance_tags }}"
        image: "{{ image }}"
        wait: yes
        region: "{{ region }}"
        keypair: "{{ keypair }}"
        assign_public_ip: yes
        vpc_subnet_id: "<subnet-id>"
        count: 1
        state: present
    loop: "{{ instances }}"
    register: ec2



-   name: Set LB IP fact
    set_fact:
        lb_ip: "{{item.instances[0].public_ip}}"
    with_items:
        "{{ec2.results}}"
    when: item.item.instance_tags.name == "loadBalancer"



-   name: Set domain to ip in AWS (route53)
    route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item }}"
        value: "{{lb_ip}}"
        type: A
        overwrite: yes
        wait: yes
    with_items:
        -   "{{ domain_name}}"
        -   "www.{{ domain_name}}"
