# Terminate ec2 instances
---
-   hosts: local
    connection: local
    gather_facts: False
    roles:
        - gather_aws_instances
    tasks:
        -   name: Terminate EC2 Instance(s)
            ec2:
                instance_ids: '{{ item.instance_id }}'
                state: absent
                region: "{{ region }}"
            with_items:
                "{{ ec2_facts.instances }}"
            when: item.tags.project is defined and item.tags.project == "devops"
            register: terminated_instances

        -   name: Refresh hosts/inventory to remove old EC2 isntance
            meta: refresh_inventory
