---
db_user: microblog
db_password: $6$0b8w64UexmXM$9VNh9D3s5d91gghHNEaCkrPjlVhMORZydylLwbJnd/q0ft9ndED./RLig96p0I.iPHQA8EEtSiruDkiUglMrB/
db_root_password: $6$5KJoAo19BFc$HMWgCILyk/Xw65ik0E.2m7tzYdycAQ.hHBwByBHhq02FnHhz0avD5kq.hoIKhWeZgUO.Vztla1nnjzLfdw4.c0
